window.FPP_CONFIG = {
  "siteName": "Brauns Lichtershow",
  "siteSubtitle": "Fernsteuerung für den Falcon Player",
  "statusPollMs": 10000,
  "donationPoolId": "",
  "donationCampaignName": "",
  "donationSubtitle": "Unterstütze die Lichtershow",
  "donationText": "Vielen Dank für deine Unterstützung!",
  "buyMeACoffeeUsername": "",
  "previewMode": false,
  "accessCode": "",
  "socialFacebook": "",
  "socialInstagram": "",
  "socialTiktok": "",
  "socialWhatsapp": "",
  "socialYoutube": "",
  "socialWebsite": "",
  "socialEmail": "",
  "buttonPlaylist1Text": "Playlist 1 starten",
  "buttonPlaylist2Text": "Playlist 2 starten"
};
